//lint:file-ignore * Autogenerated code
/*
BaSyx Asset Administration Shell Repository HTTP REST-API

The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API

API version: v1
Contact: constantin.ziesche@bosch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// OperationAllOf struct for OperationAllOf
type OperationAllOf struct {
	InoutputVariables []OperationVariable `json:"inoutputVariables,omitempty"`
	InputVariables    []OperationVariable `json:"inputVariables,omitempty"`
	OutputVariables   []OperationVariable `json:"outputVariables,omitempty"`
}

// NewOperationAllOf instantiates a new OperationAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationAllOf() *OperationAllOf {
	this := OperationAllOf{}
	return &this
}

// NewOperationAllOfWithDefaults instantiates a new OperationAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationAllOfWithDefaults() *OperationAllOf {
	this := OperationAllOf{}
	return &this
}

// GetInoutputVariables returns the InoutputVariables field value if set, zero value otherwise.
func (o *OperationAllOf) GetInoutputVariables() []OperationVariable {
	if o == nil || o.InoutputVariables == nil {
		var ret []OperationVariable
		return ret
	}
	return o.InoutputVariables
}

// GetInoutputVariablesOk returns a tuple with the InoutputVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationAllOf) GetInoutputVariablesOk() ([]OperationVariable, bool) {
	if o == nil || o.InoutputVariables == nil {
		return nil, false
	}
	return o.InoutputVariables, true
}

// HasInoutputVariables returns a boolean if a field has been set.
func (o *OperationAllOf) HasInoutputVariables() bool {
	if o != nil && o.InoutputVariables != nil {
		return true
	}

	return false
}

// SetInoutputVariables gets a reference to the given []OperationVariable and assigns it to the InoutputVariables field.
func (o *OperationAllOf) SetInoutputVariables(v []OperationVariable) {
	o.InoutputVariables = v
}

// GetInputVariables returns the InputVariables field value if set, zero value otherwise.
func (o *OperationAllOf) GetInputVariables() []OperationVariable {
	if o == nil || o.InputVariables == nil {
		var ret []OperationVariable
		return ret
	}
	return o.InputVariables
}

// GetInputVariablesOk returns a tuple with the InputVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationAllOf) GetInputVariablesOk() ([]OperationVariable, bool) {
	if o == nil || o.InputVariables == nil {
		return nil, false
	}
	return o.InputVariables, true
}

// HasInputVariables returns a boolean if a field has been set.
func (o *OperationAllOf) HasInputVariables() bool {
	if o != nil && o.InputVariables != nil {
		return true
	}

	return false
}

// SetInputVariables gets a reference to the given []OperationVariable and assigns it to the InputVariables field.
func (o *OperationAllOf) SetInputVariables(v []OperationVariable) {
	o.InputVariables = v
}

// GetOutputVariables returns the OutputVariables field value if set, zero value otherwise.
func (o *OperationAllOf) GetOutputVariables() []OperationVariable {
	if o == nil || o.OutputVariables == nil {
		var ret []OperationVariable
		return ret
	}
	return o.OutputVariables
}

// GetOutputVariablesOk returns a tuple with the OutputVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationAllOf) GetOutputVariablesOk() ([]OperationVariable, bool) {
	if o == nil || o.OutputVariables == nil {
		return nil, false
	}
	return o.OutputVariables, true
}

// HasOutputVariables returns a boolean if a field has been set.
func (o *OperationAllOf) HasOutputVariables() bool {
	if o != nil && o.OutputVariables != nil {
		return true
	}

	return false
}

// SetOutputVariables gets a reference to the given []OperationVariable and assigns it to the OutputVariables field.
func (o *OperationAllOf) SetOutputVariables(v []OperationVariable) {
	o.OutputVariables = v
}

func (o OperationAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.InoutputVariables != nil {
		toSerialize["inoutputVariables"] = o.InoutputVariables
	}
	if o.InputVariables != nil {
		toSerialize["inputVariables"] = o.InputVariables
	}
	if o.OutputVariables != nil {
		toSerialize["outputVariables"] = o.OutputVariables
	}
	return json.Marshal(toSerialize)
}

type NullableOperationAllOf struct {
	value *OperationAllOf
	isSet bool
}

func (v NullableOperationAllOf) Get() *OperationAllOf {
	return v.value
}

func (v *NullableOperationAllOf) Set(val *OperationAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationAllOf(val *OperationAllOf) *NullableOperationAllOf {
	return &NullableOperationAllOf{value: val, isSet: true}
}

func (v NullableOperationAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
