//lint:file-ignore * Autogenerated code
/*
BaSyx Asset Administration Shell Repository HTTP REST-API

The full description of the generic BaSyx Asset Administration Shell Repository HTTP REST-API

API version: v1
Contact: constantin.ziesche@bosch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// BasicEventElement struct for BasicEventElement
type BasicEventElement struct {
	Extensions                 []Extension                 `json:"extensions,omitempty"`
	Category                   *string                     `json:"category,omitempty"`
	Checksum                   *string                     `json:"checksum,omitempty"`
	Description                []LangString                `json:"description,omitempty"`
	DisplayName                []LangString                `json:"displayName,omitempty"`
	IdShort                    *string                     `json:"idShort,omitempty"`
	ModelType                  ModelType                   `json:"modelType"`
	Kind                       *ModelingKind               `json:"kind,omitempty"`
	SemanticId                 *Reference                  `json:"semanticId,omitempty"`
	SupplementalSemanticIds    []Reference                 `json:"supplementalSemanticIds,omitempty"`
	Qualifiers                 []Qualifier                 `json:"qualifiers,omitempty"`
	EmbeddedDataSpecifications []EmbeddedDataSpecification `json:"embeddedDataSpecifications,omitempty"`
	Direction                  Direction                   `json:"direction"`
	LastUpdate                 *string                     `json:"lastUpdate,omitempty"`
	MaxInterval                *string                     `json:"maxInterval,omitempty"`
	MessageBroker              *Reference                  `json:"messageBroker,omitempty"`
	MessageTopic               *string                     `json:"messageTopic,omitempty"`
	MinInterval                *string                     `json:"minInterval,omitempty"`
	Observed                   Reference                   `json:"observed"`
	State                      StateOfEvent                `json:"state"`
}

// NewBasicEventElement instantiates a new BasicEventElement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasicEventElement(modelType ModelType, direction Direction, observed Reference, state StateOfEvent) *BasicEventElement {
	this := BasicEventElement{}
	this.ModelType = modelType
	this.Direction = direction
	this.Observed = observed
	this.State = state
	return &this
}

// NewBasicEventElementWithDefaults instantiates a new BasicEventElement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasicEventElementWithDefaults() *BasicEventElement {
	this := BasicEventElement{}
	return &this
}

// GetExtensions returns the Extensions field value if set, zero value otherwise.
func (o *BasicEventElement) GetExtensions() []Extension {
	if o == nil || o.Extensions == nil {
		var ret []Extension
		return ret
	}
	return o.Extensions
}

// GetExtensionsOk returns a tuple with the Extensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetExtensionsOk() ([]Extension, bool) {
	if o == nil || o.Extensions == nil {
		return nil, false
	}
	return o.Extensions, true
}

// HasExtensions returns a boolean if a field has been set.
func (o *BasicEventElement) HasExtensions() bool {
	if o != nil && o.Extensions != nil {
		return true
	}

	return false
}

// SetExtensions gets a reference to the given []Extension and assigns it to the Extensions field.
func (o *BasicEventElement) SetExtensions(v []Extension) {
	o.Extensions = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *BasicEventElement) GetCategory() string {
	if o == nil || o.Category == nil {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetCategoryOk() (*string, bool) {
	if o == nil || o.Category == nil {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *BasicEventElement) HasCategory() bool {
	if o != nil && o.Category != nil {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *BasicEventElement) SetCategory(v string) {
	o.Category = &v
}

// GetChecksum returns the Checksum field value if set, zero value otherwise.
func (o *BasicEventElement) GetChecksum() string {
	if o == nil || o.Checksum == nil {
		var ret string
		return ret
	}
	return *o.Checksum
}

// GetChecksumOk returns a tuple with the Checksum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetChecksumOk() (*string, bool) {
	if o == nil || o.Checksum == nil {
		return nil, false
	}
	return o.Checksum, true
}

// HasChecksum returns a boolean if a field has been set.
func (o *BasicEventElement) HasChecksum() bool {
	if o != nil && o.Checksum != nil {
		return true
	}

	return false
}

// SetChecksum gets a reference to the given string and assigns it to the Checksum field.
func (o *BasicEventElement) SetChecksum(v string) {
	o.Checksum = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BasicEventElement) GetDescription() []LangString {
	if o == nil || o.Description == nil {
		var ret []LangString
		return ret
	}
	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetDescriptionOk() ([]LangString, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BasicEventElement) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given []LangString and assigns it to the Description field.
func (o *BasicEventElement) SetDescription(v []LangString) {
	o.Description = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *BasicEventElement) GetDisplayName() []LangString {
	if o == nil || o.DisplayName == nil {
		var ret []LangString
		return ret
	}
	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetDisplayNameOk() ([]LangString, bool) {
	if o == nil || o.DisplayName == nil {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *BasicEventElement) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given []LangString and assigns it to the DisplayName field.
func (o *BasicEventElement) SetDisplayName(v []LangString) {
	o.DisplayName = v
}

// GetIdShort returns the IdShort field value if set, zero value otherwise.
func (o *BasicEventElement) GetIdShort() string {
	if o == nil || o.IdShort == nil {
		var ret string
		return ret
	}
	return *o.IdShort
}

// GetIdShortOk returns a tuple with the IdShort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetIdShortOk() (*string, bool) {
	if o == nil || o.IdShort == nil {
		return nil, false
	}
	return o.IdShort, true
}

// HasIdShort returns a boolean if a field has been set.
func (o *BasicEventElement) HasIdShort() bool {
	if o != nil && o.IdShort != nil {
		return true
	}

	return false
}

// SetIdShort gets a reference to the given string and assigns it to the IdShort field.
func (o *BasicEventElement) SetIdShort(v string) {
	o.IdShort = &v
}

// GetModelType returns the ModelType field value
func (o *BasicEventElement) GetModelType() ModelType {
	if o == nil {
		var ret ModelType
		return ret
	}

	return o.ModelType
}

// GetModelTypeOk returns a tuple with the ModelType field value
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetModelTypeOk() (*ModelType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelType, true
}

// SetModelType sets field value
func (o *BasicEventElement) SetModelType(v ModelType) {
	o.ModelType = v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *BasicEventElement) GetKind() ModelingKind {
	if o == nil || o.Kind == nil {
		var ret ModelingKind
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetKindOk() (*ModelingKind, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *BasicEventElement) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given ModelingKind and assigns it to the Kind field.
func (o *BasicEventElement) SetKind(v ModelingKind) {
	o.Kind = &v
}

// GetSemanticId returns the SemanticId field value if set, zero value otherwise.
func (o *BasicEventElement) GetSemanticId() Reference {
	if o == nil || o.SemanticId == nil {
		var ret Reference
		return ret
	}
	return *o.SemanticId
}

// GetSemanticIdOk returns a tuple with the SemanticId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetSemanticIdOk() (*Reference, bool) {
	if o == nil || o.SemanticId == nil {
		return nil, false
	}
	return o.SemanticId, true
}

// HasSemanticId returns a boolean if a field has been set.
func (o *BasicEventElement) HasSemanticId() bool {
	if o != nil && o.SemanticId != nil {
		return true
	}

	return false
}

// SetSemanticId gets a reference to the given Reference and assigns it to the SemanticId field.
func (o *BasicEventElement) SetSemanticId(v Reference) {
	o.SemanticId = &v
}

// GetSupplementalSemanticIds returns the SupplementalSemanticIds field value if set, zero value otherwise.
func (o *BasicEventElement) GetSupplementalSemanticIds() []Reference {
	if o == nil || o.SupplementalSemanticIds == nil {
		var ret []Reference
		return ret
	}
	return o.SupplementalSemanticIds
}

// GetSupplementalSemanticIdsOk returns a tuple with the SupplementalSemanticIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetSupplementalSemanticIdsOk() ([]Reference, bool) {
	if o == nil || o.SupplementalSemanticIds == nil {
		return nil, false
	}
	return o.SupplementalSemanticIds, true
}

// HasSupplementalSemanticIds returns a boolean if a field has been set.
func (o *BasicEventElement) HasSupplementalSemanticIds() bool {
	if o != nil && o.SupplementalSemanticIds != nil {
		return true
	}

	return false
}

// SetSupplementalSemanticIds gets a reference to the given []Reference and assigns it to the SupplementalSemanticIds field.
func (o *BasicEventElement) SetSupplementalSemanticIds(v []Reference) {
	o.SupplementalSemanticIds = v
}

// GetQualifiers returns the Qualifiers field value if set, zero value otherwise.
func (o *BasicEventElement) GetQualifiers() []Qualifier {
	if o == nil || o.Qualifiers == nil {
		var ret []Qualifier
		return ret
	}
	return o.Qualifiers
}

// GetQualifiersOk returns a tuple with the Qualifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetQualifiersOk() ([]Qualifier, bool) {
	if o == nil || o.Qualifiers == nil {
		return nil, false
	}
	return o.Qualifiers, true
}

// HasQualifiers returns a boolean if a field has been set.
func (o *BasicEventElement) HasQualifiers() bool {
	if o != nil && o.Qualifiers != nil {
		return true
	}

	return false
}

// SetQualifiers gets a reference to the given []Qualifier and assigns it to the Qualifiers field.
func (o *BasicEventElement) SetQualifiers(v []Qualifier) {
	o.Qualifiers = v
}

// GetEmbeddedDataSpecifications returns the EmbeddedDataSpecifications field value if set, zero value otherwise.
func (o *BasicEventElement) GetEmbeddedDataSpecifications() []EmbeddedDataSpecification {
	if o == nil || o.EmbeddedDataSpecifications == nil {
		var ret []EmbeddedDataSpecification
		return ret
	}
	return o.EmbeddedDataSpecifications
}

// GetEmbeddedDataSpecificationsOk returns a tuple with the EmbeddedDataSpecifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetEmbeddedDataSpecificationsOk() ([]EmbeddedDataSpecification, bool) {
	if o == nil || o.EmbeddedDataSpecifications == nil {
		return nil, false
	}
	return o.EmbeddedDataSpecifications, true
}

// HasEmbeddedDataSpecifications returns a boolean if a field has been set.
func (o *BasicEventElement) HasEmbeddedDataSpecifications() bool {
	if o != nil && o.EmbeddedDataSpecifications != nil {
		return true
	}

	return false
}

// SetEmbeddedDataSpecifications gets a reference to the given []EmbeddedDataSpecification and assigns it to the EmbeddedDataSpecifications field.
func (o *BasicEventElement) SetEmbeddedDataSpecifications(v []EmbeddedDataSpecification) {
	o.EmbeddedDataSpecifications = v
}

// GetDirection returns the Direction field value
func (o *BasicEventElement) GetDirection() Direction {
	if o == nil {
		var ret Direction
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetDirectionOk() (*Direction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *BasicEventElement) SetDirection(v Direction) {
	o.Direction = v
}

// GetLastUpdate returns the LastUpdate field value if set, zero value otherwise.
func (o *BasicEventElement) GetLastUpdate() string {
	if o == nil || o.LastUpdate == nil {
		var ret string
		return ret
	}
	return *o.LastUpdate
}

// GetLastUpdateOk returns a tuple with the LastUpdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetLastUpdateOk() (*string, bool) {
	if o == nil || o.LastUpdate == nil {
		return nil, false
	}
	return o.LastUpdate, true
}

// HasLastUpdate returns a boolean if a field has been set.
func (o *BasicEventElement) HasLastUpdate() bool {
	if o != nil && o.LastUpdate != nil {
		return true
	}

	return false
}

// SetLastUpdate gets a reference to the given string and assigns it to the LastUpdate field.
func (o *BasicEventElement) SetLastUpdate(v string) {
	o.LastUpdate = &v
}

// GetMaxInterval returns the MaxInterval field value if set, zero value otherwise.
func (o *BasicEventElement) GetMaxInterval() string {
	if o == nil || o.MaxInterval == nil {
		var ret string
		return ret
	}
	return *o.MaxInterval
}

// GetMaxIntervalOk returns a tuple with the MaxInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetMaxIntervalOk() (*string, bool) {
	if o == nil || o.MaxInterval == nil {
		return nil, false
	}
	return o.MaxInterval, true
}

// HasMaxInterval returns a boolean if a field has been set.
func (o *BasicEventElement) HasMaxInterval() bool {
	if o != nil && o.MaxInterval != nil {
		return true
	}

	return false
}

// SetMaxInterval gets a reference to the given string and assigns it to the MaxInterval field.
func (o *BasicEventElement) SetMaxInterval(v string) {
	o.MaxInterval = &v
}

// GetMessageBroker returns the MessageBroker field value if set, zero value otherwise.
func (o *BasicEventElement) GetMessageBroker() Reference {
	if o == nil || o.MessageBroker == nil {
		var ret Reference
		return ret
	}
	return *o.MessageBroker
}

// GetMessageBrokerOk returns a tuple with the MessageBroker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetMessageBrokerOk() (*Reference, bool) {
	if o == nil || o.MessageBroker == nil {
		return nil, false
	}
	return o.MessageBroker, true
}

// HasMessageBroker returns a boolean if a field has been set.
func (o *BasicEventElement) HasMessageBroker() bool {
	if o != nil && o.MessageBroker != nil {
		return true
	}

	return false
}

// SetMessageBroker gets a reference to the given Reference and assigns it to the MessageBroker field.
func (o *BasicEventElement) SetMessageBroker(v Reference) {
	o.MessageBroker = &v
}

// GetMessageTopic returns the MessageTopic field value if set, zero value otherwise.
func (o *BasicEventElement) GetMessageTopic() string {
	if o == nil || o.MessageTopic == nil {
		var ret string
		return ret
	}
	return *o.MessageTopic
}

// GetMessageTopicOk returns a tuple with the MessageTopic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetMessageTopicOk() (*string, bool) {
	if o == nil || o.MessageTopic == nil {
		return nil, false
	}
	return o.MessageTopic, true
}

// HasMessageTopic returns a boolean if a field has been set.
func (o *BasicEventElement) HasMessageTopic() bool {
	if o != nil && o.MessageTopic != nil {
		return true
	}

	return false
}

// SetMessageTopic gets a reference to the given string and assigns it to the MessageTopic field.
func (o *BasicEventElement) SetMessageTopic(v string) {
	o.MessageTopic = &v
}

// GetMinInterval returns the MinInterval field value if set, zero value otherwise.
func (o *BasicEventElement) GetMinInterval() string {
	if o == nil || o.MinInterval == nil {
		var ret string
		return ret
	}
	return *o.MinInterval
}

// GetMinIntervalOk returns a tuple with the MinInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetMinIntervalOk() (*string, bool) {
	if o == nil || o.MinInterval == nil {
		return nil, false
	}
	return o.MinInterval, true
}

// HasMinInterval returns a boolean if a field has been set.
func (o *BasicEventElement) HasMinInterval() bool {
	if o != nil && o.MinInterval != nil {
		return true
	}

	return false
}

// SetMinInterval gets a reference to the given string and assigns it to the MinInterval field.
func (o *BasicEventElement) SetMinInterval(v string) {
	o.MinInterval = &v
}

// GetObserved returns the Observed field value
func (o *BasicEventElement) GetObserved() Reference {
	if o == nil {
		var ret Reference
		return ret
	}

	return o.Observed
}

// GetObservedOk returns a tuple with the Observed field value
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetObservedOk() (*Reference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Observed, true
}

// SetObserved sets field value
func (o *BasicEventElement) SetObserved(v Reference) {
	o.Observed = v
}

// GetState returns the State field value
func (o *BasicEventElement) GetState() StateOfEvent {
	if o == nil {
		var ret StateOfEvent
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *BasicEventElement) GetStateOk() (*StateOfEvent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *BasicEventElement) SetState(v StateOfEvent) {
	o.State = v
}

func (o BasicEventElement) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Extensions != nil {
		toSerialize["extensions"] = o.Extensions
	}
	if o.Category != nil {
		toSerialize["category"] = o.Category
	}
	if o.Checksum != nil {
		toSerialize["checksum"] = o.Checksum
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.DisplayName != nil {
		toSerialize["displayName"] = o.DisplayName
	}
	if o.IdShort != nil {
		toSerialize["idShort"] = o.IdShort
	}
	if true {
		toSerialize["modelType"] = o.ModelType
	}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.SemanticId != nil {
		toSerialize["semanticId"] = o.SemanticId
	}
	if o.SupplementalSemanticIds != nil {
		toSerialize["supplementalSemanticIds"] = o.SupplementalSemanticIds
	}
	if o.Qualifiers != nil {
		toSerialize["qualifiers"] = o.Qualifiers
	}
	if o.EmbeddedDataSpecifications != nil {
		toSerialize["embeddedDataSpecifications"] = o.EmbeddedDataSpecifications
	}
	if true {
		toSerialize["direction"] = o.Direction
	}
	if o.LastUpdate != nil {
		toSerialize["lastUpdate"] = o.LastUpdate
	}
	if o.MaxInterval != nil {
		toSerialize["maxInterval"] = o.MaxInterval
	}
	if o.MessageBroker != nil {
		toSerialize["messageBroker"] = o.MessageBroker
	}
	if o.MessageTopic != nil {
		toSerialize["messageTopic"] = o.MessageTopic
	}
	if o.MinInterval != nil {
		toSerialize["minInterval"] = o.MinInterval
	}
	if true {
		toSerialize["observed"] = o.Observed
	}
	if true {
		toSerialize["state"] = o.State
	}
	return json.Marshal(toSerialize)
}

type NullableBasicEventElement struct {
	value *BasicEventElement
	isSet bool
}

func (v NullableBasicEventElement) Get() *BasicEventElement {
	return v.value
}

func (v *NullableBasicEventElement) Set(val *BasicEventElement) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicEventElement) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicEventElement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicEventElement(val *BasicEventElement) *NullableBasicEventElement {
	return &NullableBasicEventElement{value: val, isSet: true}
}

func (v NullableBasicEventElement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicEventElement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
