//lint:file-ignore * Autogenerated code
/*
BaSyx Asset Administration Shell HTTP REST-API

The full description of the generic BaSyx Asset Administration Shell HTTP REST-API

API version: v1
Contact: constantin.ziesche@bosch.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// AssetAdministrationShellDescriptor struct for AssetAdministrationShellDescriptor
type AssetAdministrationShellDescriptor struct {
	Administration *AdministrativeInformation `json:"administration,omitempty"`
	Asset          *Asset                     `json:"asset,omitempty"`
	Category       NullableString             `json:"category,omitempty"`
	Description    []LangString               `json:"description,omitempty"`
	Endpoints      []IEndpoint                `json:"endpoints,omitempty"`
	IdShort        NullableString             `json:"idShort,omitempty"`
	Identification *Identifier                `json:"identification,omitempty"`
	ModelType      *ModelType                 `json:"modelType,omitempty"`
	Submodels      []SubmodelDescriptor       `json:"submodels,omitempty"`
}

// NewAssetAdministrationShellDescriptor instantiates a new AssetAdministrationShellDescriptor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetAdministrationShellDescriptor() *AssetAdministrationShellDescriptor {
	this := AssetAdministrationShellDescriptor{}
	return &this
}

// NewAssetAdministrationShellDescriptorWithDefaults instantiates a new AssetAdministrationShellDescriptor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetAdministrationShellDescriptorWithDefaults() *AssetAdministrationShellDescriptor {
	this := AssetAdministrationShellDescriptor{}
	return &this
}

// GetAdministration returns the Administration field value if set, zero value otherwise.
func (o *AssetAdministrationShellDescriptor) GetAdministration() AdministrativeInformation {
	if o == nil || o.Administration == nil {
		var ret AdministrativeInformation
		return ret
	}
	return *o.Administration
}

// GetAdministrationOk returns a tuple with the Administration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetAdministrationShellDescriptor) GetAdministrationOk() (*AdministrativeInformation, bool) {
	if o == nil || o.Administration == nil {
		return nil, false
	}
	return o.Administration, true
}

// HasAdministration returns a boolean if a field has been set.
func (o *AssetAdministrationShellDescriptor) HasAdministration() bool {
	if o != nil && o.Administration != nil {
		return true
	}

	return false
}

// SetAdministration gets a reference to the given AdministrativeInformation and assigns it to the Administration field.
func (o *AssetAdministrationShellDescriptor) SetAdministration(v AdministrativeInformation) {
	o.Administration = &v
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *AssetAdministrationShellDescriptor) GetAsset() Asset {
	if o == nil || o.Asset == nil {
		var ret Asset
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetAdministrationShellDescriptor) GetAssetOk() (*Asset, bool) {
	if o == nil || o.Asset == nil {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *AssetAdministrationShellDescriptor) HasAsset() bool {
	if o != nil && o.Asset != nil {
		return true
	}

	return false
}

// SetAsset gets a reference to the given Asset and assigns it to the Asset field.
func (o *AssetAdministrationShellDescriptor) SetAsset(v Asset) {
	o.Asset = &v
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssetAdministrationShellDescriptor) GetCategory() string {
	if o == nil || o.Category.Get() == nil {
		var ret string
		return ret
	}
	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssetAdministrationShellDescriptor) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// HasCategory returns a boolean if a field has been set.
func (o *AssetAdministrationShellDescriptor) HasCategory() bool {
	if o != nil && o.Category.IsSet() {
		return true
	}

	return false
}

// SetCategory gets a reference to the given NullableString and assigns it to the Category field.
func (o *AssetAdministrationShellDescriptor) SetCategory(v string) {
	o.Category.Set(&v)
}

// SetCategoryNil sets the value for Category to be an explicit nil
func (o *AssetAdministrationShellDescriptor) SetCategoryNil() {
	o.Category.Set(nil)
}

// UnsetCategory ensures that no value is present for Category, not even an explicit nil
func (o *AssetAdministrationShellDescriptor) UnsetCategory() {
	o.Category.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssetAdministrationShellDescriptor) GetDescription() []LangString {
	if o == nil {
		var ret []LangString
		return ret
	}
	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssetAdministrationShellDescriptor) GetDescriptionOk() ([]LangString, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AssetAdministrationShellDescriptor) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given []LangString and assigns it to the Description field.
func (o *AssetAdministrationShellDescriptor) SetDescription(v []LangString) {
	o.Description = v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssetAdministrationShellDescriptor) GetEndpoints() []IEndpoint {
	if o == nil {
		var ret []IEndpoint
		return ret
	}
	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssetAdministrationShellDescriptor) GetEndpointsOk() ([]IEndpoint, bool) {
	if o == nil || o.Endpoints == nil {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *AssetAdministrationShellDescriptor) HasEndpoints() bool {
	if o != nil && o.Endpoints != nil {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given []IEndpoint and assigns it to the Endpoints field.
func (o *AssetAdministrationShellDescriptor) SetEndpoints(v []IEndpoint) {
	o.Endpoints = v
}

// GetIdShort returns the IdShort field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssetAdministrationShellDescriptor) GetIdShort() string {
	if o == nil || o.IdShort.Get() == nil {
		var ret string
		return ret
	}
	return *o.IdShort.Get()
}

// GetIdShortOk returns a tuple with the IdShort field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssetAdministrationShellDescriptor) GetIdShortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IdShort.Get(), o.IdShort.IsSet()
}

// HasIdShort returns a boolean if a field has been set.
func (o *AssetAdministrationShellDescriptor) HasIdShort() bool {
	if o != nil && o.IdShort.IsSet() {
		return true
	}

	return false
}

// SetIdShort gets a reference to the given NullableString and assigns it to the IdShort field.
func (o *AssetAdministrationShellDescriptor) SetIdShort(v string) {
	o.IdShort.Set(&v)
}

// SetIdShortNil sets the value for IdShort to be an explicit nil
func (o *AssetAdministrationShellDescriptor) SetIdShortNil() {
	o.IdShort.Set(nil)
}

// UnsetIdShort ensures that no value is present for IdShort, not even an explicit nil
func (o *AssetAdministrationShellDescriptor) UnsetIdShort() {
	o.IdShort.Unset()
}

// GetIdentification returns the Identification field value if set, zero value otherwise.
func (o *AssetAdministrationShellDescriptor) GetIdentification() Identifier {
	if o == nil || o.Identification == nil {
		var ret Identifier
		return ret
	}
	return *o.Identification
}

// GetIdentificationOk returns a tuple with the Identification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetAdministrationShellDescriptor) GetIdentificationOk() (*Identifier, bool) {
	if o == nil || o.Identification == nil {
		return nil, false
	}
	return o.Identification, true
}

// HasIdentification returns a boolean if a field has been set.
func (o *AssetAdministrationShellDescriptor) HasIdentification() bool {
	if o != nil && o.Identification != nil {
		return true
	}

	return false
}

// SetIdentification gets a reference to the given Identifier and assigns it to the Identification field.
func (o *AssetAdministrationShellDescriptor) SetIdentification(v Identifier) {
	o.Identification = &v
}

// GetModelType returns the ModelType field value if set, zero value otherwise.
func (o *AssetAdministrationShellDescriptor) GetModelType() ModelType {
	if o == nil || o.ModelType == nil {
		var ret ModelType
		return ret
	}
	return *o.ModelType
}

// GetModelTypeOk returns a tuple with the ModelType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetAdministrationShellDescriptor) GetModelTypeOk() (*ModelType, bool) {
	if o == nil || o.ModelType == nil {
		return nil, false
	}
	return o.ModelType, true
}

// HasModelType returns a boolean if a field has been set.
func (o *AssetAdministrationShellDescriptor) HasModelType() bool {
	if o != nil && o.ModelType != nil {
		return true
	}

	return false
}

// SetModelType gets a reference to the given ModelType and assigns it to the ModelType field.
func (o *AssetAdministrationShellDescriptor) SetModelType(v ModelType) {
	o.ModelType = &v
}

// GetSubmodels returns the Submodels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssetAdministrationShellDescriptor) GetSubmodels() []SubmodelDescriptor {
	if o == nil {
		var ret []SubmodelDescriptor
		return ret
	}
	return o.Submodels
}

// GetSubmodelsOk returns a tuple with the Submodels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssetAdministrationShellDescriptor) GetSubmodelsOk() ([]SubmodelDescriptor, bool) {
	if o == nil || o.Submodels == nil {
		return nil, false
	}
	return o.Submodels, true
}

// HasSubmodels returns a boolean if a field has been set.
func (o *AssetAdministrationShellDescriptor) HasSubmodels() bool {
	if o != nil && o.Submodels != nil {
		return true
	}

	return false
}

// SetSubmodels gets a reference to the given []SubmodelDescriptor and assigns it to the Submodels field.
func (o *AssetAdministrationShellDescriptor) SetSubmodels(v []SubmodelDescriptor) {
	o.Submodels = v
}

func (o AssetAdministrationShellDescriptor) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Administration != nil {
		toSerialize["administration"] = o.Administration
	}
	if o.Asset != nil {
		toSerialize["asset"] = o.Asset
	}
	if o.Category.IsSet() {
		toSerialize["category"] = o.Category.Get()
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Endpoints != nil {
		toSerialize["endpoints"] = o.Endpoints
	}
	if o.IdShort.IsSet() {
		toSerialize["idShort"] = o.IdShort.Get()
	}
	if o.Identification != nil {
		toSerialize["identification"] = o.Identification
	}
	if o.ModelType != nil {
		toSerialize["modelType"] = o.ModelType
	}
	if o.Submodels != nil {
		toSerialize["submodels"] = o.Submodels
	}
	return json.Marshal(toSerialize)
}

type NullableAssetAdministrationShellDescriptor struct {
	value *AssetAdministrationShellDescriptor
	isSet bool
}

func (v NullableAssetAdministrationShellDescriptor) Get() *AssetAdministrationShellDescriptor {
	return v.value
}

func (v *NullableAssetAdministrationShellDescriptor) Set(val *AssetAdministrationShellDescriptor) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetAdministrationShellDescriptor) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetAdministrationShellDescriptor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetAdministrationShellDescriptor(val *AssetAdministrationShellDescriptor) *NullableAssetAdministrationShellDescriptor {
	return &NullableAssetAdministrationShellDescriptor{value: val, isSet: true}
}

func (v NullableAssetAdministrationShellDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetAdministrationShellDescriptor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
