name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.18
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install staticcheck@2022.1.1
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@2022.1.1
    - uses: actions/checkout@v3
    - name: Run Tests
      run: |
          make lint
          make test
